### ISSUE TITLE
ESPHome Support

### ISSUE THREAD

**Issue by oldgeezy** [mcer12/Hugh-ESP8266#28]
I just converted a bunch of my Tasmota devices to ESPHome, which looks like a great platform for managing all your ESP devices and OTA updates.  Is there any way we could get firmware support there for our switches?

**Comment by mcer12** [comment]
Hi, since there are some unusual hardware specifics (buttons connected to wakeup, capacitors on buttons etc), you can't use ESPHome fw as is, you would have to make your own custom sketch to accomodate the above. If you would like to contribute with an ESPHome sketch, I will accept PRs, but I don't have the time to learn ESPHome as I don't personally use that platform at home... hope you understand :)

That said, if you use ESPHome with Home Assistant, you can use the MQTT sketch which works pretty well with HASS including auto-discovery.
